format = """
$directory\
$git_branch\
$character"""

add_newline = false

[directory]
format = "[$path]($style) "
style = "bold blue"
truncate_to_repo = true

[git_branch]
format = "[$branch]($style) "
style = "bold yellow"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
