format = """
$username\
$hostname\
$directory\
$git_branch\
$python\
[](bold blue) """

add_newline = false

[git_branch]
format = "on [$branch]($style) "

[cmd_duration]
format = "[$duration]($style) "

[python]
format = "[$virtualenv]($style) "
