set -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",screen-256color:Tc"

set -g mouse on
setw -g mode-keys vi

set -g base-index 1
set -g renumber-windows on

set-option -g status-interval 1
set-option -g status-left ''
set-option -g status-right ''

set -g window-status-format " #I#{?#{!=:#{window_name},Window},: #W,} "
set -g window-status-style "bg=default,fg=white"
set -g window-status-last-style "bg=default,fg=white"
set -g window-status-activity-style "bg=yellow,fg=black"
set -g window-status-bell-style "bg=yellow,fg=black"
set -gF window-status-separator "#[bg=default,fg=brightblack,none]│"
set -g status-position bottom
set -g status-style "bg=default"
set -g status-justify "left"
set -g window-status-current-format " #I#{?#{!=:#{window_name},Window},: #W,} "
set -g window-status-current-style "bg=brightwhite,fg=black"
set -g mode-style "bg=brightwhite,fg=black"
set -g pane-active-border-style "bg=default,fg=black"
set -g pane-border-style "bg=default,fg=black"

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"
