set -g  default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:RGB"

set -g mouse on

set -g status-position top
set -g status-style fg="#d3c6aa",bg="#272e33"

set -g status-left " ❐ [#S] | "
set -g  status-right "#[fg=#d3c6aa,bg=#272e33] #(top -l 1 | grep -E "^CPU" | sed 's/.*://')"

set -g window-status-current-format "#[bg=#3c4841,fg=#d3c6aa] #I #W #[bg=#272e33,fg=#d3c6aa]"
set -g window-status-format " #I #W "

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind r source-file ~/.config/tmux/tmux.conf
bind - split-window -v
bind | split-window -h
