set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on

set -g prefix C-s
bind C-s send-prefix

setw -g mode-keys vi

bind-key h resize-pane -L 10
bind-key j resize-pane -D 10
bind-key k resize-pane -U 10
bind-key l resize-pane -R 10

bind-key X kill-session

set-option -g base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'TanglingTreats/tmux-everforest'

set -g @tmux-everforest 'dark-medium'

run '~/.tmux/plugins/tpm/tpm'
